version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance_chat_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=finance
      - POSTGRES_PASSWORD=finance123
      - POSTGRES_DB=finance_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance -d finance_chat"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis-data: 